### ISSUE TITLE
[Proposal] Big input images support

### ISSUE THREAD

**Issue by air55555** [satoshi-ikehata/SDM-UniPS-CVPR2023#4]
we are trying to process 5000x5000 images. Only cropped to 1024x1024 could be processed in 3060 gpu. Is it possible to somehow make parallel computations on 4 GPUs?
![image](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/2674008/6de6fc30-7e4c-4343-b1fc-0040c62e3ffe)

**Comment by satoshi-ikehata** [comment]
If you have specified the --scalable option, increasing the image resolution beyond 512x512 should not  cause the increase of GPU memory consumption.

**Comment by air55555** [comment]
Satoshi ! i tried --scalable. still have no memory even for 4096 pix. Initial imgs are 5700 px;).
C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Scripts\python.exe C:/Users/LRS/PycharmProjects/SDM-UniPS-CVPR2023/sdm_unips/main.py --target normal --session_name 38_HQ --test_dir .\case_38_HQ\ --checkpoint .\checkpoint\ --max_image_res 4096 --max_image_num 15 --scalable

Starting a session: 38_HQ
target: normal

Loading pretrained model... .\checkpoint\/normal\nml.pytmodel 

canonical resolution: 256 x 256  
pixel samples: 10000

Exploring .\case_38_HQ\
Found 1 objects!

Testing on A.data
image index: [13 10  9  3  6 11  7 12  8  1  4  5 14  2  0]
original crop size: 5759 x 5758
resized crop size: 4096 x 4096
number of images: 15 / 15 (max)

Recovering normal map(s): 1 / 64
Traceback (most recent call last):
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\main.py", line 60, in <module>
    main()
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\main.py", line 48, in main
    sdf_unips.run(testdata=test_data,
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\builder\builder.py", line 99, in run
    nout, _, _, _  = self.net_nml(pI, pM, nImgArray.reshape(-1,1), decoder_resolution = patch_size * torch.ones(pI.shape[0],1), canonical_resolution=canonical_resolution* torch.ones(pI.shape[0],1))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\model\model.py", line 279, in forward
    x = self.glc_aggregation(x)  #[len(ids), 384]       
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\model\model.py", line 133, in forward
    x = self.aggregation(x)      
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\model\transformer.py", line 202, in forward
    x = self.enc(x)
        ^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\model\transformer.py", line 150, in forward
    return self.mab(X, X)
           ^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\venv\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LRS\PycharmProjects\SDM-UniPS-CVPR2023\sdm_unips\modules\model\transformer.py", line 141, in forward
    O = O + self.dropout2(self.fc_o2(self.dropout1(F.gelu(self.fc_o1(O_))))) 
                                                   ^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 570.00 MiB (GPU 0; 12.00 GiB total capacity; 10.16 GiB already allocated; 0 bytes free; 10.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Process finished with exit code 1

**Comment by satoshi-ikehata** [comment]
Can you try reducing the number of input images e.g., to 10? If it still causes a memory shortage, something strange is happening.

**Comment by air55555** [comment]
well done! 5000 pix output normal map
![image](https://github.com/satoshi-ikehata/SDM-UniPS-CVPR2023/assets/2674008/08010d31-6a3c-4955-9912-298ec43128e7)
