### ISSUE TITLE
test Error

### ISSUE THREAD

**Issue by MyraBaba** [satoshi-ikehata/SDM-UniPS-CVPR2023#9]
python sdm_unips/main.py --session_name bullet_1 --test_dir no_mask/  --checkpoint checkpoint

Starting a session: bullet_1
target: normal_and_brdf

Loading pretrained model... checkpoint/normal/nml.pytmodel
Loading pretrained model... checkpoint/brdf/brdf.pytmodel

canonical resolution: 256 x 256
pixel samples: 10000

Exploring no_mask/
Found 4 objects!

Testing on alligator.data
image index: [2 5 3 1 0 4]
original crop size: 3999 x 3998
resized crop size: 3584 x 3584
number of images: 6 / 10 (max)

Recovering normal_and_brdf map(s) 1 / 1
Traceback (most recent call last):
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/main.py", line 60, in <module>
    main()
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/main.py", line 48, in main
    sdf_unips.run(testdata=test_data,
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/modules/builder/builder.py", line 130, in run
    nout, _, _, _  = self.net_nml(I, M, nImgArray.reshape(-1,1), decoder_resolution=testdata.data.h * torch.ones(I.shape[0],1), canonical_resolution=canonical_resolution* torch.ones(I.shape[0],1))
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/modules/model/model.py", line 226, in forward
    glc = self.image_encoder(data, nImgArray, canonical_resolution) # torch.Size([B, N, 256, H/4, W/4]) [img, mask]
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/modules/model/model.py", line 93, in forward
    x_resized = F.interpolate(x, size= (canonical_resolution, canonical_resolution), mode='bilinear', align_corners=True)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/functional.py", line 3942, in interpolate
    raise TypeError(
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.ndarray'>, <class 'numpy.ndarray'>]

**Comment by satoshi-ikehata** [comment]
It seems that canonical_resolution is cast as a numpy.ndarray. You can solve the issue by simply casting it as an integer.

**Comment by MyraBaba** [comment]
I casted : nout, _, _, _ = self.net_nml(I, M, nImgArray.reshape(-1, 1),
                             decoder_resolution=testdata.data.h * torch.ones(I.shape[0], 1),
                             canonical_resolution=(canonical_resolution * torch.ones(I.shape[0], 1)).int())


same error.


Even your example images is not working

**Comment by satoshi-ikehata** [comment]
torch.tensor.int() is still torch.tensor. Please try canonical_resolution.item() to convert array to scalar.

**Comment by MyraBaba** [comment]
nout, _, _, _ = self.net_nml(I, M, nImgArray.reshape(-1, 1),
                                                     decoder_resolution=testdata.data.h * torch.ones(I.shape[0], 1),
                                                     canonical_resolution=(canonical_resolution * torch.ones(I.shape[0],
                                                                                                             1)).item())



Found 1 objects!

Testing on bullet.data
image index: [20 17 37 16 36 33 29 26  6 28  4 31 11 13  1 15 22  3 25  9]
original crop size: 3455 x 3454
resized crop size: 3072 x 3072
number of images: 20 / 20 (max)

Recovering normal_and_brdf map(s) 1 / 1
Traceback (most recent call last):
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/main.py", line 60, in <module>
    main()
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/main.py", line 48, in main
    sdf_unips.run(testdata=test_data,
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/modules/builder/builder.py", line 130, in run
    nout, _, _, _ = self.net_nml(I, M, nImgArray.reshape(-1, 1),
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bc/Projects/Universal-PS-CVPR2022/UniversalPS/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bc/Projects/SDM-UniPS-CVPR2023/sdm_unips/modules/model/model.py", line 213, in forward
    canonical_resolution = canonical_resolution[0,0].cpu().numpy().astype(np.int32)
TypeError: 'float' object is not subscriptable

**Comment by MyraBaba** [comment]
@satoshi-ikehata 

how we ca run your example no_mask images , still errors
